services:
  specmatic:
    image: specmatic/specmatic:latest
    container_name: appwrite-specmatic
    depends_on:
      appwrite:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - ../specs:/usr/src/specs
    working_dir: /usr/src/app
    command: test --host appwrite --port 80
    networks:
      - appwrite

  specmatic-validate:
    image: specmatic/specmatic:latest
    container_name: appwrite-specmatic-validate
    volumes:
      - .:/usr/src/app
      - ../specs:/usr/src/specs
    working_dir: /usr/src/app
    command: examples validate
    networks:
      - appwrite
